--------------------Eliminacion de las tablas------------------------------------------------
DROP TABLE JUGADOR CASCADE CONSTRAINTS;
DROP TABLE ENTRENADOR CASCADE CONSTRAINTS;
DROP TABLE ASISTENTE CASCADE CONSTRAINTS;
DROP TABLE EQUIPO CASCADE CONSTRAINTS;
DROP TABLE DUEÑO CASCADE CONSTRAINTS;
DROP TABLE LIGA CASCADE CONSTRAINTS;
DROP TABLE JORNADA CASCADE CONSTRAINTS;
DROP TABLE PARTIDO CASCADE CONSTRAINTS;
DROP TABLE PERFIL CASCADE CONSTRAINTS;
DROP TABLE CLASIFICACION CASCADE CONSTRAINTS;
DROP TABLE EQUIPO_PARTIDO CASCADE CONSTRAINTS;

-------------------Creacion de las tablas....................................................
CREATE TABLE PERFIL (
	COD_PERFIL NUMBER(4),
	NOMBRE VARCHAR2(20),
	CONTRASEÑA VARCHAR2(20)
	CONSTRAINT PER_PK PRIMARY KEY(COD_PERFIL)
);

CREATE TABLE LIGA (
	ID_LIGA VARCHAR2(4),
	NOMBRE VARCHAR2(20),
	CATEGORIA VARCHAR2(15),
	CANT_EQUIPOS NUMBER(2),
	ESTADO VARCHAR2(15),
	CONSTRAINT LIG_PK PRIMARY KEY(ID_LIGA)
);

CREATE TABLE ENTRENADOR (
	ID_ENTRENADOR VARCHAR2(4),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	NICKNAME VARCHAR2(20),
	FECHA_NAC DATE,
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT ENT_PK PRIMARY KEY
);

CREATE TABLE ASISTENTE(
	ID_ASISTENTE VARCHAR2(4),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	NICKNAME VARCHAR2(20),
	FECHA_NAC DATE,
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20)
	CONSTRAINT JUG_PK PRIMARY KEY(ID_JUGADOR)
);

CREATE TABLE EQUIPO(
	ID_EQUIPO VARCHAR2(4),
	NOMBRE VARCHAR2(20),
	NUM_JUGADORES NUMBER(),
	SALARIO_ANUAL NUMBER(6),
	ID_ENTRENADOR VARCHAR2(4),
	ID_ASISTENTE VARCHAR2(4),
	ID_LIGA VARCHAR2(4),
	CONSTRAINT EQU_PK PRIMARY KEY(ID_EQUIPOD),
	CONSTRAINT EQU_ENT_FK FOREIGN KEY (ID_ENTRENADOR)
				REFERENCES ENTRENADOR(ID_ENTRENADOR) ON DELETE CASCADE,
	CONSTRAINT EQU_ASI_FK FOREIGN KEY (ID_ASISTENTE)
				REFERENCES ASISTENTE(ID_ASISTENTE) ON DELETE CASCADE,
	CONSTRAINT EQU_LIG_FK FOREIGN KEY (ID_LIGA)
				REFERENCES LIGA(ID_LIGA) ON DELETE CASCADE			
);


CREATE TABLE JUGADOR (
	ID_JUGADOR VARCHAR2(4),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	NICKNAME VARCHAR2(20),
	FECHA_NAC DATE,
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	ROL VARCHAR2(),
	ID_EQUIPO VARCHAR2(4),
	CONSTRAINT JUG_PK PRIMARY KEY,
	CONSTRAINT JUG_EQU_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE
);

CREATE TABLE DUEÑO (
	ID_DUEÑO VARCHAR2(4),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	DIRECCION VARCHAR2(35),
	TELEFONO VARCHAR2(20),
	FECHA_NAC DATE,
	ID_EQUIPO VARCHAR2(4),
	CONSTRAINT DUE_PK PRIMARY KEY(ID_DUEÑO),
	CONSTRAINT EQU_LIG_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES DUEÑO(ID_EQUIPO) ON DELETE CASCADE
);

CREATE TABLE CLASIFICACION (
	NOMBRE_EQUIPO VARCHAR2(4)
	PARTIDOS_JUGADOS NUMBER(2),
	PARTIDOS_GANADOS NUMBER(2),
	PARTIDOS_PERDIDOS NUMBER(2),
	PUNTUACION NUMBER(4),
	DIFERENCIA_PUNTUACION NUMBER(4),
	ID_LIGA VARCHAR2(4),
	CONSTRAINT CLA_PK PRIMARY KEY(NOMBRE_EQUIPO),
	CONSTRAINT CLA_LIG_FK FOREIGN KEY (ID_LIGA)
				REFERENCES LIGA(ID_LIGA) ON DELETE CASCADE
);

CREATE TABLE JORNADA (
	NUM_JORNADA NUMBER(4),
	NUM_PARTIDOS NUMBER(4),
	FECHA DATE,
	ID_LIGA VARCHAR2(4),
	CONSTRAINT JOR_PK PRIMARY KEY(NUM_JORNADA),
	CONSTRAINT JOR_LIG_FK FOREIGN KEY (ID_LIGA)
				REFERENCES LIGA(ID_LIGA) ON DELETE CASCADE
);

CREATE TABLE PARTIDO (
	ID_PARTIDO VARCHAR2(4),
	HORA TIME,
	NUM_JORNADA NUMBER(4),
	CONSTRAINT PAR_PK PRIMARY KEY(ID_PARTIDO),
	CONSTRAINT PAR_JOR_FK FOREIGN KEY (NUM_JORNADA)
				REFERENCES JORNADA(NUM_JORNADA) ON DELETE CASCADE
);

CREATE TABLE EQUIPO_PARTIDO (
	ID_EQUIPO VARCHAR2(4),
	COD_PARTIDO VARCHAR2(4),
	NUM_EQUIPO2 VARCHAR2(4),
	RESULTADO VARCHAR2(20), 
	CONSTRAINT EQU_PAR_PK PRIMARY KEY(ID_EQUIPO, COD_PARTIDO),
	CONSTRAINT PAR_JOR_IDE_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE,
	CONSTRAINT PAR_JOR_COD_FK FOREIGN KEY (COD_PARTIDO)
				REFERENCES PARTIDO(ID_PARTIDO) ON DELETE CASCADE,
	CONSTRAINT PAR_JOR_NUM_FK FOREIGN KEY (NUM_EQUIPO2)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE,			
)