--------------------Eliminacion de las tablas------------------------------------------------
DROP TABLE JUGADOR CASCADE CONSTRAINTS;
DROP TABLE ENTRENADOR CASCADE CONSTRAINTS;
DROP TABLE ASISTENTE CASCADE CONSTRAINTS;
DROP TABLE EQUIPO CASCADE CONSTRAINTS;
DROP TABLE DUEÑO CASCADE CONSTRAINTS;
DROP TABLE JORNADA CASCADE CONSTRAINTS;
DROP TABLE PARTIDO CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRADOR CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;


-------------------Creacion de las tablas....................................................
CREATE TABLE ADMINISTRADOR (
	COD_ADMIN NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
						),
	CORREO VARCHAR2(30),
	CONTRASEÑA VARCHAR2(20)
	CONSTRAINT ADM_PK PRIMARY KEY(COD_ADMIN)
);
 
CREATE TABLE USUARIO (
	COD_USUARIO NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
						),
	CORREO VARCHAR2(30),
	CONTRASEÑA VARCHAR2(20)
	CONSTRAINT USU_PK PRIMARY KEY(COD_USUARIO)
);

CREATE TABLE ENTRENADOR (
	ID_ENTRENADOR VARCHAR2(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	ID_EQUIPO VARCHAR2(4),
	CONSTRAINT ENT_PK PRIMARY KEY(ID_ENTRENADOR)
	CONSTRAINT NET_EQU_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE
);

CREATE TABLE ASISTENTE(
	ID_ASISTENTE VARCHAR2(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
					),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20)
	CONSTRAINT JUG_PK PRIMARY KEY(ID_ASISTENTE)
	CONSTRAINT ASI_ENT_FK FOREIGN KEY (ID_ASISTENTE)
				REFERENCES ENTRENADOR(ID_ENTRENADOR) ON DELETE CASCADE
);

CREATE TABLE EQUIPO(
	ID_EQUIPO VARCHAR2(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	NOMBRE VARCHAR2(20),
	ESCUDO VARCHAR2(50),
	CONSTRAINT EQU_PK PRIMARY KEY(ID_EQUIPOD)		
);


CREATE TABLE JUGADOR (
	ID_JUGADOR VARCHAR2(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	NICKNAME VARCHAR2(20),
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	ROL VARCHAR2(30),
	ID_EQUIPO VARCHAR2(4),
	CONSTRAINT JUG_PK PRIMARY KEY,
	CONSTRAINT JUG_EQU_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE

);

CREATE TABLE DUENO (
	ID_DUEÑO VARCHAR2(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	TELEFONO VARCHAR2(20),
	ID_EQUIPO VARCHAR2(4),
	CONSTRAINT DUE_PK PRIMARY KEY(ID_DUEÑO),
	CONSTRAINT EQU_LIG_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES DUEÑO(ID_EQUIPO) ON DELETE CASCADE
);


CREATE TABLE JORNADA (
	NUM_JORNADA NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	FECHA DATE,
	CONSTRAINT JOR_PK PRIMARY KEY(NUM_JORNADA)
);

CREATE TABLE PARTIDO (
	ID_PARTIDO VARCHAR2(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	HORA TIME,
	RESULTADOL VARCHAR2(24),
	RESULTADOV VARCHAR2(24),
	NUM_JORNADA NUMBER(4),
	ID_EQUIPOL VARCHAR2(4),
	ID_EQUIPOV VARCHAR2(4),
	CONSTRAINT PAR_PK PRIMARY KEY(ID_PARTIDO),
	CONSTRAINT PAR_JOR_FK FOREIGN KEY (NUM_JORNADA)
				REFERENCES JORNADA(NUM_JORNADA) ON DELETE CASCADE
	CONSTRAINT PAR_EQUL_FK FOREIGN KEY (ID_EQUIPOL)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE
	CONSTRAINT PAR_EQUV_FK FOREIGN KEY (ID_EQUIPOV)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE
);
