DROP TABLE JUGADOR CASCADE CONSTRAINTS;
DROP TABLE ENTRENADOR CASCADE CONSTRAINTS;
DROP TABLE ASISTENTE CASCADE CONSTRAINTS;
DROP TABLE EQUIPO CASCADE CONSTRAINTS;
DROP TABLE DUENO CASCADE CONSTRAINTS;
DROP TABLE JORNADA CASCADE CONSTRAINTS;
DROP TABLE PARTIDO CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRADOR CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;


-------------------Creacion de las tablas....................................................
CREATE TABLE ADMINISTRADOR (
	COD_ADMIN NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
						),
	CORREO VARCHAR2(30),
	CONTRASEÑA VARCHAR2(20),
	CONSTRAINT ADM_PK PRIMARY KEY(COD_ADMIN)
);
 
CREATE TABLE USUARIO (
	COD_USUARIO NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
						),
	CORREO VARCHAR2(30),
	CONTRASEÑA VARCHAR2(20),
	CONSTRAINT USU_PK PRIMARY KEY(COD_USUARIO)
);

CREATE TABLE EQUIPO(
	ID_EQUIPO NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	NOMBRE VARCHAR2(20),
	ESCUDO VARCHAR2(50),
	CONSTRAINT EQU_PK PRIMARY KEY(ID_EQUIPO)		
);

CREATE TABLE ENTRENADOR (
	ID_ENTRENADOR NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	ID_EQUIPO NUMBER(4),
	CONSTRAINT ENT_PK PRIMARY KEY(ID_ENTRENADOR),
	CONSTRAINT NET_EQU_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE
);

CREATE TABLE ASISTENTE(
	ID_ASISTENTE NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
					),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT ASI_PK PRIMARY KEY(ID_ASISTENTE),
	CONSTRAINT ASI_ENT_FK FOREIGN KEY (ID_ASISTENTE)
				REFERENCES ENTRENADOR(ID_ENTRENADOR) ON DELETE CASCADE
);




CREATE TABLE JUGADOR (
	ID_JUGADOR NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	NOMBRE VARCHAR2(20),
	SUELDO NUMBER(6),
	NICKNAME VARCHAR2(20),
	TELEFONO VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	ROL VARCHAR2(30),
	ID_EQUIPO NUMBER(4),
	CONSTRAINT JUG_PK PRIMARY KEY(ID_JUGADOR),
	CONSTRAINT JUG_EQU_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE

);

CREATE TABLE DUENO (
	ID_DUENO NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	TELEFONO VARCHAR2(20),
	ID_EQUIPO NUMBER(4),
	CONSTRAINT DUE_PK PRIMARY KEY(ID_DUENO),
	CONSTRAINT DUE_EQU_FK FOREIGN KEY (ID_EQUIPO)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE
);


CREATE TABLE JORNADA (
	NUM_JORNADA NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	FECHA DATE,
	CONSTRAINT JOR_PK PRIMARY KEY(NUM_JORNADA)
);

CREATE TABLE PARTIDO (
	ID_PARTIDO NUMBER(4) GENERATED AS IDENTITY(
									START WITH 1
									INCREMENT BY 1
									MAXVALUE 1000
									NOCYCLE
		),
	HORA DATE,
	RESULTADOL VARCHAR2(24),
	RESULTADOV VARCHAR2(24),
	NUM_JORNADA NUMBER(4),
	ID_EQUIPOL NUMBER(4),
	ID_EQUIPOV NUMBER(4),
	CONSTRAINT PAR_PK PRIMARY KEY(ID_PARTIDO),
	CONSTRAINT PAR_JOR_FK FOREIGN KEY (NUM_JORNADA)
				REFERENCES JORNADA(NUM_JORNADA) ON DELETE CASCADE,
	CONSTRAINT PAR_EQUL_FK FOREIGN KEY (ID_EQUIPOL)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE,
	CONSTRAINT PAR_EQUV_FK FOREIGN KEY (ID_EQUIPOV)
				REFERENCES EQUIPO(ID_EQUIPO) ON DELETE CASCADE
);

INSERT INTO EQUIPO(NOMBRE,ESCUDO) VALUES ('PSG','http://imagenescudopsg.es');
INSERT INTO EQUIPO(NOMBRE,ESCUDO) VALUES ('REAL MADRID','http://imagenescudorealmadrid.es');

