CREATE OR REPLACE TRIGGER MIN_MAX_JUGADORES 
AFTER INSERT OR UPDATE ON EQUIPO
DECLARE 
	V_ERROR VARCHAR2(250);

BEGIN
	SELECT NUM_JUGADORES
	FROM EQUIPO;
	CASE
		 WHEN INSERTING THEN
			IF NUM_JUGADORES > 6 THEN
				RAISE_APPLICATION_ERROR(-20500,'No puede haber mas de 6 jugadores en un equipo');
			END IF;
		WHEN UPDATING THEN
			IF NUM_JUGADORES = 6 THEN
				RAISE_APPLICATION_ERROR(-20500,'No puede haber mas de 6 jugadores en un equipo');
			END IF;
	END CASE;		
EXCEPTION 
	WHEN OTHERS THEN 
		 V_ERROR:='Error Oracle: '||TO_CHAR(SQLCODE)||', '||SQLERRM;
        RAISE_APPLICATION_ERROR('-20000' ,v_error);
END;


