/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import projecto.Controlador;
import projecto.Controlador.Rol;

/**
 *
 * @author ketro
 */

public class Vprincipal extends javax.swing.JFrame {
    Border borde_defecto = BorderFactory.createMatteBorder(1,1, 1, 1, new Color(51,51,51));
    Border borde_amarillo = BorderFactory.createMatteBorder(1,1, 1, 1, Color.YELLOW);
    JLabel[] menuLabel = new JLabel[5];
    JPanel[] paneles = new JPanel[6];
    
    int xx;
    int xy;
    /**
     * Creates new form Vprincipal
     */
    public Vprincipal() {}
    public Vprincipal(Rol rol, String nombre) {
        initComponents();
        this.setLocationRelativeTo(null);
        lNombreUsuario.setText(nombre);
        tipoVista(rol);
        addActionToMenuTables();
        añadirAccionAlMenuIntegrantes();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/descarga.png")).getImage());
        menuLabel[0] = lJornadas;
        menuLabel[1] = lClasificaciones;
        menuLabel[2] = lEquipos;
        menuLabel[3] = lIntegrantes;
        menuLabel[4] = lPerfiles;
        
        paneles[0] = pPrincipal;
        paneles[1] = pJornadas;
        paneles[2] = pClasificaciones;
        paneles[3] = pEquipos;
        paneles[5] = pPerfiles;
        
        pDesplegableIntegrantes.setVisible(false);
    }
     private void tipoVista(Controlador.Rol rol){
        switch (rol){
            case USUARIO:
                this.lEquipos.setVisible(false);
                this.lIntegrantes.setVisible(false);
                this.lPerfiles.setVisible(false);
                break;
            default:
                break;
        }
        
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pMenu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lClasificaciones = new javax.swing.JLabel();
        lEquipos = new javax.swing.JLabel();
        lJornadas = new javax.swing.JLabel();
        lPerfiles = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lIntegrantes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lMinimizar = new javax.swing.JLabel();
        lCerrar = new javax.swing.JLabel();
        lNombreUsuario = new javax.swing.JLabel();
        pDesplegableIntegrantes = new javax.swing.JPanel();
        lJugadores = new javax.swing.JLabel();
        lDueño = new javax.swing.JLabel();
        lEntrenadores = new javax.swing.JLabel();
        lAsistenes = new javax.swing.JLabel();
        pPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lIntegrantes2 = new javax.swing.JLabel();
        pJornadas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pClasificaciones = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pEquipos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jToolBar10 = new javax.swing.JToolBar();
        lInsertarEquipo = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        lBorrarEquipo = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        lModificarEquipo = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        lConsultarEquipo = new javax.swing.JLabel();
        pJugadores = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jToolBar4 = new javax.swing.JToolBar();
        lInsertarJugador = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lBorrarJugador = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lModificarJugador = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lConsultarJugador = new javax.swing.JLabel();
        pEntrenadores = new javax.swing.JPanel();
        jToolBar5 = new javax.swing.JToolBar();
        lInsertarEntrenadores = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lBorrarEntrenador = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lModificarEntrenador = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lConsultarEntrenador = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pAsistentes = new javax.swing.JPanel();
        jToolBar6 = new javax.swing.JToolBar();
        lInsertarAsistentes = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        lBorrarAsistente = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lModificarAsistente = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        lConsultarAsistente = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pDueño = new javax.swing.JPanel();
        jToolBar7 = new javax.swing.JToolBar();
        lInsertarDueño = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        lBorrarDueño = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        lModificarDueño = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        lConsultarDueño = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pPerfiles = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jToolBar11 = new javax.swing.JToolBar();
        lInsertarUsuario = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        lBorrarUsuario = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        lModificarUsuario = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        lConsultarUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pMenu.setBackground(new java.awt.Color(51, 51, 51));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(205, 205, 205));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fallo-ilustracion-mando-joystick-aislado-efectos-ruido-sobre-fondo-oscuro_168425-94.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vit Vit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lClasificaciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lClasificaciones.setForeground(new java.awt.Color(255, 255, 255));
        lClasificaciones.setText("  Clasificaciones");

        lEquipos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lEquipos.setForeground(new java.awt.Color(255, 255, 255));
        lEquipos.setText("  Equipos");

        lJornadas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lJornadas.setForeground(new java.awt.Color(255, 255, 255));
        lJornadas.setText("  Jornadas");

        lPerfiles.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lPerfiles.setForeground(new java.awt.Color(255, 255, 255));
        lPerfiles.setText("  Perfiles");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logout_37127.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        lIntegrantes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lIntegrantes.setForeground(new java.awt.Color(255, 255, 255));
        lIntegrantes.setText("  Integrantes");

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lPerfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lClasificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lJornadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lEquipos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10))
                    .addComponent(lIntegrantes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lClasificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(16, 16, 16))
        );

        jPanel1.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 520));

        jPanel4.setBackground(new java.awt.Color(6, 57, 113));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lMinimizar.setBackground(new java.awt.Color(6, 57, 113));
        lMinimizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lMinimizar.setText("_");
        lMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lMinimizarMouseClicked(evt);
            }
        });
        jPanel4.add(lMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -10, 20, 30));

        lCerrar.setBackground(new java.awt.Color(6, 57, 113));
        lCerrar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCerrar.setText("X");
        lCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCerrarMouseClicked(evt);
            }
        });
        jPanel4.add(lCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        lNombreUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 30));

        pDesplegableIntegrantes.setBackground(new java.awt.Color(51, 51, 51));
        pDesplegableIntegrantes.setForeground(new java.awt.Color(51, 51, 51));

        lJugadores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lJugadores.setText("  Jugadores");

        lDueño.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lDueño.setForeground(new java.awt.Color(255, 255, 255));
        lDueño.setText("  Dueño");

        lEntrenadores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lEntrenadores.setForeground(new java.awt.Color(255, 255, 255));
        lEntrenadores.setText("  Entrenadores");

        lAsistenes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lAsistenes.setForeground(new java.awt.Color(255, 255, 255));
        lAsistenes.setText("  Asistentes");

        javax.swing.GroupLayout pDesplegableIntegrantesLayout = new javax.swing.GroupLayout(pDesplegableIntegrantes);
        pDesplegableIntegrantes.setLayout(pDesplegableIntegrantesLayout);
        pDesplegableIntegrantesLayout.setHorizontalGroup(
            pDesplegableIntegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lDueño, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(lEntrenadores, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(lAsistenes, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        pDesplegableIntegrantesLayout.setVerticalGroup(
            pDesplegableIntegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDesplegableIntegrantesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEntrenadores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lAsistenes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jPanel1.add(pDesplegableIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 180, 200));

        pPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido !");

        lIntegrantes2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lIntegrantes2.setForeground(new java.awt.Color(255, 255, 255));
        lIntegrantes2.setText("  Integrantes");

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addComponent(lIntegrantes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(146, 146, 146))
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(356, 356, 356)
                .addComponent(lIntegrantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        pJornadas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Jornadas");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout pJornadasLayout = new javax.swing.GroupLayout(pJornadas);
        pJornadas.setLayout(pJornadasLayout);
        pJornadasLayout.setHorizontalGroup(
            pJornadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJornadasLayout.createSequentialGroup()
                .addGroup(pJornadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pJornadasLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel2))
                    .addGroup(pJornadasLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pJornadasLayout.setVerticalGroup(
            pJornadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJornadasLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel1.add(pJornadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        pClasificaciones.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Clasificaciones");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pClasificacionesLayout = new javax.swing.GroupLayout(pClasificaciones);
        pClasificaciones.setLayout(pClasificacionesLayout);
        pClasificacionesLayout.setHorizontalGroup(
            pClasificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClasificacionesLayout.createSequentialGroup()
                .addGroup(pClasificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pClasificacionesLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pClasificacionesLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel3)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pClasificacionesLayout.setVerticalGroup(
            pClasificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClasificacionesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel1.add(pClasificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        pEquipos.setBackground(new java.awt.Color(255, 255, 255));
        pEquipos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Equipos");
        pEquipos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 87, -1, -1));

        jToolBar10.setRollover(true);

        lInsertarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486564407-plus-green_81521.png"))); // NOI18N
        lInsertarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lInsertarEquipoMouseClicked(evt);
            }
        });
        jToolBar10.add(lInsertarEquipo);

        jLabel75.setText("  ");
        jToolBar10.add(jLabel75);

        lBorrarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar-plugins-wordpress.png"))); // NOI18N
        lBorrarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBorrarEquipoMouseClicked(evt);
            }
        });
        jToolBar10.add(lBorrarEquipo);

        jLabel77.setText("  ");
        jToolBar10.add(jLabel77);

        lModificarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-icon-2375785_640.png"))); // NOI18N
        lModificarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lModificarEquipoMouseClicked(evt);
            }
        });
        jToolBar10.add(lModificarEquipo);

        jLabel79.setText("  ");
        jToolBar10.add(jLabel79);

        lConsultarEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas.png"))); // NOI18N
        lConsultarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConsultarEquipoMouseClicked(evt);
            }
        });
        jToolBar10.add(lConsultarEquipo);

        pEquipos.add(jToolBar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        jPanel1.add(pEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        pJugadores.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Jugadores");

        jToolBar4.setRollover(true);

        lInsertarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486564407-plus-green_81521.png"))); // NOI18N
        lInsertarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lInsertarJugadorMouseClicked(evt);
            }
        });
        jToolBar4.add(lInsertarJugador);

        jLabel33.setText("  ");
        jToolBar4.add(jLabel33);

        lBorrarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar-plugins-wordpress.png"))); // NOI18N
        lBorrarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBorrarJugadorMouseClicked(evt);
            }
        });
        jToolBar4.add(lBorrarJugador);

        jLabel35.setText("  ");
        jToolBar4.add(jLabel35);

        lModificarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-icon-2375785_640.png"))); // NOI18N
        lModificarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lModificarJugadorMouseClicked(evt);
            }
        });
        jToolBar4.add(lModificarJugador);

        jLabel37.setText("  ");
        jToolBar4.add(jLabel37);

        lConsultarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas.png"))); // NOI18N
        lConsultarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConsultarJugadorMouseClicked(evt);
            }
        });
        jToolBar4.add(lConsultarJugador);

        javax.swing.GroupLayout pJugadoresLayout = new javax.swing.GroupLayout(pJugadores);
        pJugadores.setLayout(pJugadoresLayout);
        pJugadoresLayout.setHorizontalGroup(
            pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJugadoresLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel13)
                .addContainerGap(256, Short.MAX_VALUE))
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pJugadoresLayout.setVerticalGroup(
            pJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJugadoresLayout.createSequentialGroup()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel13)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        jPanel1.add(pJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        pEntrenadores.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar5.setRollover(true);

        lInsertarEntrenadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486564407-plus-green_81521.png"))); // NOI18N
        lInsertarEntrenadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lInsertarEntrenadoresMouseClicked(evt);
            }
        });
        jToolBar5.add(lInsertarEntrenadores);

        jLabel40.setText("  ");
        jToolBar5.add(jLabel40);

        lBorrarEntrenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar-plugins-wordpress.png"))); // NOI18N
        lBorrarEntrenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBorrarEntrenadorMouseClicked(evt);
            }
        });
        jToolBar5.add(lBorrarEntrenador);

        jLabel42.setText("  ");
        jToolBar5.add(jLabel42);

        lModificarEntrenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-icon-2375785_640.png"))); // NOI18N
        lModificarEntrenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lModificarEntrenadorMouseClicked(evt);
            }
        });
        jToolBar5.add(lModificarEntrenador);

        jLabel44.setText("  ");
        jToolBar5.add(jLabel44);

        lConsultarEntrenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas.png"))); // NOI18N
        lConsultarEntrenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConsultarEntrenadorMouseClicked(evt);
            }
        });
        jToolBar5.add(lConsultarEntrenador);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Entrenadores");

        javax.swing.GroupLayout pEntrenadoresLayout = new javax.swing.GroupLayout(pEntrenadores);
        pEntrenadores.setLayout(pEntrenadoresLayout);
        pEntrenadoresLayout.setHorizontalGroup(
            pEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pEntrenadoresLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel7)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        pEntrenadoresLayout.setVerticalGroup(
            pEntrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEntrenadoresLayout.createSequentialGroup()
                .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel7)
                .addGap(0, 367, Short.MAX_VALUE))
        );

        jPanel1.add(pEntrenadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        pAsistentes.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar6.setRollover(true);

        lInsertarAsistentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486564407-plus-green_81521.png"))); // NOI18N
        lInsertarAsistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lInsertarAsistentesMouseClicked(evt);
            }
        });
        jToolBar6.add(lInsertarAsistentes);

        jLabel47.setText("  ");
        jToolBar6.add(jLabel47);

        lBorrarAsistente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar-plugins-wordpress.png"))); // NOI18N
        lBorrarAsistente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBorrarAsistenteMouseClicked(evt);
            }
        });
        jToolBar6.add(lBorrarAsistente);

        jLabel49.setText("  ");
        jToolBar6.add(jLabel49);

        lModificarAsistente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-icon-2375785_640.png"))); // NOI18N
        lModificarAsistente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lModificarAsistenteMouseClicked(evt);
            }
        });
        jToolBar6.add(lModificarAsistente);

        jLabel51.setText("  ");
        jToolBar6.add(jLabel51);

        lConsultarAsistente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas.png"))); // NOI18N
        lConsultarAsistente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConsultarAsistenteMouseClicked(evt);
            }
        });
        jToolBar6.add(lConsultarAsistente);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("Asistentes");

        javax.swing.GroupLayout pAsistentesLayout = new javax.swing.GroupLayout(pAsistentes);
        pAsistentes.setLayout(pAsistentesLayout);
        pAsistentesLayout.setHorizontalGroup(
            pAsistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar6, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAsistentesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(243, 243, 243))
        );
        pAsistentesLayout.setVerticalGroup(
            pAsistentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAsistentesLayout.createSequentialGroup()
                .addComponent(jToolBar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel18)
                .addGap(0, 335, Short.MAX_VALUE))
        );

        jPanel1.add(pAsistentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        pDueño.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar7.setRollover(true);

        lInsertarDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486564407-plus-green_81521.png"))); // NOI18N
        lInsertarDueño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lInsertarDueñoMouseClicked(evt);
            }
        });
        jToolBar7.add(lInsertarDueño);

        jLabel54.setText("  ");
        jToolBar7.add(jLabel54);

        lBorrarDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar-plugins-wordpress.png"))); // NOI18N
        lBorrarDueño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBorrarDueñoMouseClicked(evt);
            }
        });
        jToolBar7.add(lBorrarDueño);

        jLabel56.setText("  ");
        jToolBar7.add(jLabel56);

        lModificarDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-icon-2375785_640.png"))); // NOI18N
        lModificarDueño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lModificarDueñoMouseClicked(evt);
            }
        });
        jToolBar7.add(lModificarDueño);

        jLabel58.setText("  ");
        jToolBar7.add(jLabel58);

        lConsultarDueño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas.png"))); // NOI18N
        lConsultarDueño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConsultarDueñoMouseClicked(evt);
            }
        });
        jToolBar7.add(lConsultarDueño);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setText("Dueño");

        javax.swing.GroupLayout pDueñoLayout = new javax.swing.GroupLayout(pDueño);
        pDueño.setLayout(pDueñoLayout);
        pDueñoLayout.setHorizontalGroup(
            pDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar7, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(pDueñoLayout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDueñoLayout.setVerticalGroup(
            pDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDueñoLayout.createSequentialGroup()
                .addComponent(jToolBar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel19)
                .addGap(0, 357, Short.MAX_VALUE))
        );

        jPanel1.add(pDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        pPerfiles.setBackground(new java.awt.Color(255, 255, 255));
        pPerfiles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Perfiles");
        pPerfiles.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 87, -1, -1));

        jToolBar11.setRollover(true);

        lInsertarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1486564407-plus-green_81521.png"))); // NOI18N
        lInsertarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lInsertarUsuarioMouseClicked(evt);
            }
        });
        jToolBar11.add(lInsertarUsuario);

        jLabel82.setText("  ");
        jToolBar11.add(jLabel82);

        lBorrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar-plugins-wordpress.png"))); // NOI18N
        lBorrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBorrarUsuarioMouseClicked(evt);
            }
        });
        jToolBar11.add(lBorrarUsuario);

        jLabel84.setText("  ");
        jToolBar11.add(jLabel84);

        lModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-icon-2375785_640.png"))); // NOI18N
        lModificarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lModificarUsuarioMouseClicked(evt);
            }
        });
        jToolBar11.add(lModificarUsuario);

        jLabel86.setText("  ");
        jToolBar11.add(jLabel86);

        lConsultarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas.png"))); // NOI18N
        lConsultarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lConsultarUsuarioMouseClicked(evt);
            }
        });
        jToolBar11.add(lConsultarUsuario);

        pPerfiles.add(jToolBar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        jPanel1.add(pPerfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 620, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lCerrarMouseClicked

    private void lMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMinimizarMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lMinimizarMouseClicked

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       Controlador.cerrarSesion();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void lInsertarAsistentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lInsertarAsistentesMouseClicked
        Controlador.abrirInsertarAsistente();
    }//GEN-LAST:event_lInsertarAsistentesMouseClicked

    private void lInsertarEntrenadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lInsertarEntrenadoresMouseClicked
        Controlador.abrirInsertarEntrenador();
    }//GEN-LAST:event_lInsertarEntrenadoresMouseClicked

    private void lInsertarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lInsertarJugadorMouseClicked
        Controlador.abrirInsertarJugador();
    }//GEN-LAST:event_lInsertarJugadorMouseClicked

    private void lInsertarDueñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lInsertarDueñoMouseClicked
        try {
            Controlador.abrirInsertarDueno();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_lInsertarDueñoMouseClicked

    private void lInsertarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lInsertarEquipoMouseClicked
        Controlador.abrirInsertarEquipo();
    }//GEN-LAST:event_lInsertarEquipoMouseClicked

    private void lInsertarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lInsertarUsuarioMouseClicked
        Controlador.abrirInsertarUsuario();
    }//GEN-LAST:event_lInsertarUsuarioMouseClicked

    private void lModificarAsistenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lModificarAsistenteMouseClicked
        Controlador.abrirModificarAsistente();
    }//GEN-LAST:event_lModificarAsistenteMouseClicked

    private void lModificarDueñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lModificarDueñoMouseClicked
        Controlador.abrirModificarDueño();
    }//GEN-LAST:event_lModificarDueñoMouseClicked

    private void lModificarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lModificarUsuarioMouseClicked
        Controlador.abrirModificarUsuario();
    }//GEN-LAST:event_lModificarUsuarioMouseClicked

    private void lModificarEntrenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lModificarEntrenadorMouseClicked
        Controlador.abrirModificarEntrenador();
    }//GEN-LAST:event_lModificarEntrenadorMouseClicked

    private void lModificarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lModificarJugadorMouseClicked
        Controlador.abrirModificarJugador();
    }//GEN-LAST:event_lModificarJugadorMouseClicked

    private void lModificarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lModificarEquipoMouseClicked
       try{
            
           Controlador.abrirModificarEquipos();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_lModificarEquipoMouseClicked

    private void lBorrarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBorrarEquipoMouseClicked
        try{
            String nombre = JOptionPane.showInputDialog("Introduzca el nombre del equipo que desees eliminar");
            Controlador.abrirEliminarEquipo(nombre);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lBorrarEquipoMouseClicked

    private void lBorrarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBorrarJugadorMouseClicked
        try{
            String nombre = JOptionPane.showInputDialog("Introducza el nombre del equipo que desees eliminar");
            Controlador.abrirEliminarJugador(nombre);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lBorrarJugadorMouseClicked

    private void lBorrarEntrenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBorrarEntrenadorMouseClicked
        try{
            String nombre = JOptionPane.showInputDialog("Introducza el nombre del equipo que desees eliminar");
            Controlador.abrirEliminarEntrenador(nombre);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lBorrarEntrenadorMouseClicked

    private void lBorrarAsistenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBorrarAsistenteMouseClicked
       try{
            String nombre = JOptionPane.showInputDialog("Introducza el nombre del equipo que desees eliminar");
            Controlador.abrirEliminarAsistente(nombre);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lBorrarAsistenteMouseClicked

    private void lBorrarDueñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBorrarDueñoMouseClicked
        try{
            String nombre = JOptionPane.showInputDialog("Introducza el nombre del equipo que desees eliminar");
            Controlador.abrirEliminarDueno(nombre);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lBorrarDueñoMouseClicked

    private void lBorrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBorrarUsuarioMouseClicked
        try{
            String nombre = JOptionPane.showInputDialog("Introducza el nombre del equipo que desees eliminar");
            Controlador.abrirEliminarUsuario(nombre);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lBorrarUsuarioMouseClicked

    private void lConsultarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConsultarEquipoMouseClicked
        Controlador.abrirConsultarEquipo();
    }//GEN-LAST:event_lConsultarEquipoMouseClicked

    private void lConsultarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConsultarJugadorMouseClicked
        Controlador.abrirConsultarJugadores();
    }//GEN-LAST:event_lConsultarJugadorMouseClicked

    private void lConsultarEntrenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConsultarEntrenadorMouseClicked
        Controlador.abrirConsultarEntrenador();
    }//GEN-LAST:event_lConsultarEntrenadorMouseClicked

    private void lConsultarAsistenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConsultarAsistenteMouseClicked
        Controlador.abrirConsultarAsistente();
    }//GEN-LAST:event_lConsultarAsistenteMouseClicked

    private void lConsultarDueñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConsultarDueñoMouseClicked
        Controlador.abrirConsultarDueno();
    }//GEN-LAST:event_lConsultarDueñoMouseClicked

    private void lConsultarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lConsultarUsuarioMouseClicked
        Controlador.abrirConsultarUsuario();
    }//GEN-LAST:event_lConsultarUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vprincipal().setVisible(true);
            }
        });
    }

    public void mostrarPanelesJornadas() {
          pPrincipal.setVisible(false);
          pClasificaciones.setVisible(false);
          pEquipos.setVisible(false);
          pPerfiles.setVisible(false);
          pJornadas.setVisible(true);
          pDesplegableIntegrantes.setVisible(false);
          pJugadores.setVisible(false);
          pEntrenadores.setVisible(false);
          pAsistentes.setVisible(false);
          pDueño.setVisible(false);
    
    }
    
    public void mostrarPanelesClasificaciones() {
          pPrincipal.setVisible(false);
          pClasificaciones.setVisible(true);
          pEquipos.setVisible(false);
          pPerfiles.setVisible(false);
          pJornadas.setVisible(false);
          pDesplegableIntegrantes.setVisible(false);
          pJugadores.setVisible(false);
          pEntrenadores.setVisible(false);
          pAsistentes.setVisible(false);
          pDueño.setVisible(false);
    }
     
    public void mostrarPanelesEquipos() {
          pPrincipal.setVisible(false);
          pClasificaciones.setVisible(false);
          pEquipos.setVisible(true);
          pPerfiles.setVisible(false);
          pJornadas.setVisible(false);
          pDesplegableIntegrantes.setVisible(false);
          pJugadores.setVisible(false);
          pEntrenadores.setVisible(false);
          pAsistentes.setVisible(false);
          pDueño.setVisible(false);
    }

    public void mostrarPanelesIntegrantes() {
          pDesplegableIntegrantes.setVisible(true);
    }
     
    public void mostrarPanelesPerfiles() {
          pPrincipal.setVisible(false);
          pClasificaciones.setVisible(false);
          pEquipos.setVisible(false);
          pPerfiles.setVisible(true);
          pJornadas.setVisible(false);
          pDesplegableIntegrantes.setVisible(false);
          pJugadores.setVisible(false);
          pEntrenadores.setVisible(false);
          pAsistentes.setVisible(false);
          pDueño.setVisible(false);
    }
    
    public void mostrarPanelesIntegrantesJugadores() {
          pPrincipal.setVisible(false);
          pClasificaciones.setVisible(false);
          pEquipos.setVisible(false);
          pJornadas.setVisible(false);
          pDesplegableIntegrantes.setVisible(false);
          pJugadores.setVisible(true);
          pEntrenadores.setVisible(false);
          pAsistentes.setVisible(false);
          pDueño.setVisible(false);
    }
    
     public void mostrarPanelesIntegrantesEntrenadores() {
          pPrincipal.setVisible(false);
          pClasificaciones.setVisible(false);
          pEquipos.setVisible(false);
          pJornadas.setVisible(false);
          pDesplegableIntegrantes.setVisible(false);
          pJugadores.setVisible(false);
          pEntrenadores.setVisible(true);
          pAsistentes.setVisible(false);
          pDueño.setVisible(false);
    }
     
      public void mostrarPanelesIntegrantesAsistentes() {
          pPrincipal.setVisible(false);
          pClasificaciones.setVisible(false);
          pEquipos.setVisible(false);
          pJornadas.setVisible(false);
          pDesplegableIntegrantes.setVisible(false);
          pJugadores.setVisible(false);
          pEntrenadores.setVisible(false);
          pAsistentes.setVisible(true);
          pDueño.setVisible(false);
    }
      
     public void mostrarPanelesIntegrantesDueño() {
          pPrincipal.setVisible(false);
          pClasificaciones.setVisible(false);
          pEquipos.setVisible(false);
          pJornadas.setVisible(false);
          pDesplegableIntegrantes.setVisible(false);
          pJugadores.setVisible(false);
          pEntrenadores.setVisible(false);
          pAsistentes.setVisible(false);
          pDueño.setVisible(true);
     }
    public void setFondoLabel(JLabel label){
        for (JLabel menuLabels : menuLabel )   {
            menuLabels.setForeground(Color.white);
        }
        label.setForeground(Color.red);
    }
    
    public void addActionToMenuTables(){
        Component [] components = pMenu.getComponents();
        
        for (Component component : components){
            if(component instanceof JLabel){
                JLabel label = (JLabel) component;
                
                label.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        setFondoLabel(label);
                        
                        switch (label.getText().trim()){
                            case "Jornadas":
                                   mostrarPanelesJornadas();
                                   break;
                            case "Clasificaciones":
                                   mostrarPanelesClasificaciones();
                                   break;
                            case "Equipos":
                                   mostrarPanelesEquipos();
                                   break;         
                            case "Integrantes":
                                   mostrarPanelesIntegrantes();
                                   break;      
                            case "Perfiles":
                                   mostrarPanelesPerfiles();
                                   break;          
                        }
                    }
                    @Override
                    public void mousePressed(MouseEvent e) {
                       
                    }
                    @Override
                    public void mouseReleased(MouseEvent e) {
                       
                    }
                    @Override
                    public void mouseEntered(MouseEvent e) {
                        label.setBorder(borde_amarillo);
                    }
                    @Override
                    public void mouseExited(MouseEvent e) {
                        label.setBorder(borde_defecto);
                    }
                });
            }
        }
    }
    
     public void añadirAccionAlMenuIntegrantes(){
        Component [] components = pDesplegableIntegrantes.getComponents();
        for(Component component : components){
            if(component instanceof JLabel){
                JLabel label = (JLabel) component;
                
                label.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
         
                         switch (label.getText().trim()){
                            case "Jugadores":
                                   mostrarPanelesIntegrantesJugadores();
                                   break;
                            case "Entrenadores":
                                   mostrarPanelesIntegrantesEntrenadores();
                                   break;
                            case "Asistentes":
                                   mostrarPanelesIntegrantesAsistentes();
                                   break;         
                            case "Dueño":
                                   mostrarPanelesIntegrantesDueño();
                                   break;            
                        }

                    }

                    @Override
                    public void mousePressed(MouseEvent e) {

                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {

                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                       label.setBorder(borde_amarillo);
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        label.setBorder(borde_defecto);
                    }
                }
                );
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToolBar jToolBar10;
    private javax.swing.JToolBar jToolBar11;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JLabel lAsistenes;
    private javax.swing.JLabel lBorrarAsistente;
    private javax.swing.JLabel lBorrarDueño;
    private javax.swing.JLabel lBorrarEntrenador;
    private javax.swing.JLabel lBorrarEquipo;
    private javax.swing.JLabel lBorrarJugador;
    private javax.swing.JLabel lBorrarUsuario;
    private javax.swing.JLabel lCerrar;
    private javax.swing.JLabel lClasificaciones;
    private javax.swing.JLabel lConsultarAsistente;
    private javax.swing.JLabel lConsultarDueño;
    private javax.swing.JLabel lConsultarEntrenador;
    private javax.swing.JLabel lConsultarEquipo;
    private javax.swing.JLabel lConsultarJugador;
    private javax.swing.JLabel lConsultarUsuario;
    private javax.swing.JLabel lDueño;
    private javax.swing.JLabel lEntrenadores;
    private javax.swing.JLabel lEquipos;
    private javax.swing.JLabel lInsertarAsistentes;
    private javax.swing.JLabel lInsertarDueño;
    private javax.swing.JLabel lInsertarEntrenadores;
    private javax.swing.JLabel lInsertarEquipo;
    private javax.swing.JLabel lInsertarJugador;
    private javax.swing.JLabel lInsertarUsuario;
    private javax.swing.JLabel lIntegrantes;
    private javax.swing.JLabel lIntegrantes2;
    private javax.swing.JLabel lJornadas;
    private javax.swing.JLabel lJugadores;
    private javax.swing.JLabel lMinimizar;
    private javax.swing.JLabel lModificarAsistente;
    private javax.swing.JLabel lModificarDueño;
    private javax.swing.JLabel lModificarEntrenador;
    private javax.swing.JLabel lModificarEquipo;
    private javax.swing.JLabel lModificarJugador;
    private javax.swing.JLabel lModificarUsuario;
    private javax.swing.JLabel lNombreUsuario;
    private javax.swing.JLabel lPerfiles;
    private javax.swing.JPanel pAsistentes;
    private javax.swing.JPanel pClasificaciones;
    private javax.swing.JPanel pDesplegableIntegrantes;
    private javax.swing.JPanel pDueño;
    private javax.swing.JPanel pEntrenadores;
    private javax.swing.JPanel pEquipos;
    private javax.swing.JPanel pJornadas;
    private javax.swing.JPanel pJugadores;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pPerfiles;
    private javax.swing.JPanel pPrincipal;
    // End of variables declaration//GEN-END:variables
}
